swagger: '2.0'
info:
  description: Microservice JAVA API
  title: Microservice JAVA API
  version: 1.0.1
host: 'localhost:9090'
basePath: /api/v1/payment
schemes:
  - http
paths:
  '/check/messages/{messageId}':
    get:
      produces:
        - application/json
        - application/problem+json
      parameters:
        - description: payment's messageId
          in: path
          name: messageId
          required: true
          type: string
      responses:
        '200':
          description: check if the message has been paid
          schema:
            $ref: '#/definitions/PaymentStatus'
        '400':
          description: Bad Request
          schema:
            $ref: '#/definitions/Problem'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Problem'
        '404':
          description: Not Found
        '503':
          description: Service Unavailable
          schema:
            $ref: '#/definitions/Problem'
      tags:
        - API  Payment
      operationId: getPaymentUpdate
      summary: Check Payment Update By MessageId
  
definitions:
  Timestamp:
    type: string
    format: UTCISODateFromString
    description: A date-time field in ISO-8601 format and UTC timezone.
    x-import: '@pagopa/ts-commons/lib/dates'
    example: '2018-10-13T00:00:00.000Z'

  PaymentStatus:
    type: object
    properties:
      isPaid:
        type: boolean
        default: false
      dueDate:
        $ref: '#/definitions/Timestamp'
    required:
      - isPaid
  Problem:
    properties:
      error:
        description: |
          error description.
        format: uri
        type: string
      path:
        description: >
          An absolute URI that identifies the specific occurrence of the
          problem.
          It may or may not yield further information if dereferenced.
        type: string
      status:
        description: |
          Status code description.
        type: string
      timestamp:
        description: |
          timestamp of the error
        type: number
    type: object
securityDefinitions:
  SubscriptionKey:
    description: The API key to access this function app.
    in: header
    name: Ocp-Apim-Subscription-Key
    type: apiKey
security:
  - SubscriptionKey: []
tags:
  - description: API  Payment
    name: API  Payment
