# 
# Periodic Azure DevOps pipeline to check dependency upgraded and make a PR
#

# A pipeline with no CI trigger, just schedules
trigger: none
pr: none

parameters:
  - name: 'FUNCTION_NAME'
    displayName: 'Function name'
    type: string
    default: 'CosmosApiMessagesChangeFeed'

schedules:
  # Every day at midnight 
  - cron: "0 0 * * *"
    displayName: Daily midnight upgrade
    branches:
      include:
      - master
      - ICC-289--add-start-time-for-messages-change-feed
    always: true # Run always irrespective of changes

resources:
  repositories:
    - repository: pagopaCommons
      type: github
      name: pagopa/azure-pipeline-templates
      ref: refs/tags/v18
      endpoint: 'io-azure-devops-github-ro'


pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    echo "FUNCTION_NAME: ${ENV_FUNCTION_NAME}"
    az functionapp config appsettings set --name io-p-messages-cqrs-fn --resource-group io-p-backend-messages-rg --settings "AzureWebJobs.${ENV_FUNCTION_NAME}.Disabled=1"
  env:
    ENV_FUNCTION_NAME: '${{ parameters.FUNCTION_NAME }}'

  displayName: 'disable given function name'
