name: Code Review

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "*"
      - "!infra/*"
      - "!.github/*"
  push:
    branches:
      - CES-50-devops-decommissioning

jobs:
  deploy_on_prod:
    uses: pagopa/dx/.github/workflows/legacy_code_review.yaml@main
    name: Code Review
    secrets: inherit