name: Deploy Pipelines - PROD

on:
  workflow_dispatch:
      
jobs:
  deploy_on_prod:
    uses: pagopa/dx/.github/workflows/legacy_deploy_pipelines.yaml@main
    secrets: inherit
    with:
      environment: 'prod'
      resource_group_name: 'io-p-backend-messages-rg'
      app_name: 'io-p-messages-cqrs-fn'
      use_staging_slot: true
      use_private_agent: false
      health_check_path: '/api/v1/info'