name: Disable Change Feed Triggered Function

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

permissions:
  id-token: write
  contents: read

jobs:
  steps:
    - name: Checkout
      id: checkout
      # from https://github.com/actions/checkout/commits/main
      uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Azure Login
      uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
      with:
        client-id: "9ef6bab3-d8fc-4b31-ae21-2c36d8f92f04"
        tenant-id: "7788edaf-0346-4068-9d79-c868aed15b3d"
        subscription-id: "ec285037-c673-4f58-b594-d7c480da4e8b"
    - name: Az Cli Runner
      run: |
        az functionapp config appsettings set --name io-p-messages-cqrs-fn --resource-group io-p-backend-messages-rg --settings "AzureWebJobs.CosmosApiMessagesChangeFeed.Disabled=1"
